/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ToolboxImport } from './routes/toolbox'
import { Route as StatusImport } from './routes/status'
import { Route as SettingsImport } from './routes/settings'
import { Route as ModelsImport } from './routes/models'
import { Route as LaunchImport } from './routes/launch'
import { Route as DocsImport } from './routes/docs'
import { Route as DevtoolsImport } from './routes/devtools'
import { Route as CodexImport } from './routes/codex'
import { Route as IndexImport } from './routes/index'
import { Route as CChatIdImport } from './routes/c.$chatId'

// Create/Update Routes

const ToolboxRoute = ToolboxImport.update({
  id: '/toolbox',
  path: '/toolbox',
  getParentRoute: () => rootRoute,
} as any)

const StatusRoute = StatusImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ModelsRoute = ModelsImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRoute,
} as any)

const LaunchRoute = LaunchImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRoute,
} as any)

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const DevtoolsRoute = DevtoolsImport.update({
  id: '/devtools',
  path: '/devtools',
  getParentRoute: () => rootRoute,
} as any)

const CodexRoute = CodexImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CChatIdRoute = CChatIdImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexImport
      parentRoute: typeof rootRoute
    }
    '/devtools': {
      id: '/devtools'
      path: '/devtools'
      fullPath: '/devtools'
      preLoaderRoute: typeof DevtoolsImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchImport
      parentRoute: typeof rootRoute
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusImport
      parentRoute: typeof rootRoute
    }
    '/toolbox': {
      id: '/toolbox'
      path: '/toolbox'
      fullPath: '/toolbox'
      preLoaderRoute: typeof ToolboxImport
      parentRoute: typeof rootRoute
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/devtools': typeof DevtoolsRoute
  '/docs': typeof DocsRoute
  '/launch': typeof LaunchRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/toolbox': typeof ToolboxRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/devtools': typeof DevtoolsRoute
  '/docs': typeof DocsRoute
  '/launch': typeof LaunchRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/toolbox': typeof ToolboxRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/devtools': typeof DevtoolsRoute
  '/docs': typeof DocsRoute
  '/launch': typeof LaunchRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/toolbox': typeof ToolboxRoute
  '/c/$chatId': typeof CChatIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codex'
    | '/devtools'
    | '/docs'
    | '/launch'
    | '/models'
    | '/settings'
    | '/status'
    | '/toolbox'
    | '/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codex'
    | '/devtools'
    | '/docs'
    | '/launch'
    | '/models'
    | '/settings'
    | '/status'
    | '/toolbox'
    | '/c/$chatId'
  id:
    | '__root__'
    | '/'
    | '/codex'
    | '/devtools'
    | '/docs'
    | '/launch'
    | '/models'
    | '/settings'
    | '/status'
    | '/toolbox'
    | '/c/$chatId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodexRoute: typeof CodexRoute
  DevtoolsRoute: typeof DevtoolsRoute
  DocsRoute: typeof DocsRoute
  LaunchRoute: typeof LaunchRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  ToolboxRoute: typeof ToolboxRoute
  CChatIdRoute: typeof CChatIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodexRoute: CodexRoute,
  DevtoolsRoute: DevtoolsRoute,
  DocsRoute: DocsRoute,
  LaunchRoute: LaunchRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  ToolboxRoute: ToolboxRoute,
  CChatIdRoute: CChatIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/codex",
        "/devtools",
        "/docs",
        "/launch",
        "/models",
        "/settings",
        "/status",
        "/toolbox",
        "/c/$chatId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/codex": {
      "filePath": "codex.tsx"
    },
    "/devtools": {
      "filePath": "devtools.tsx"
    },
    "/docs": {
      "filePath": "docs.tsx"
    },
    "/launch": {
      "filePath": "launch.tsx"
    },
    "/models": {
      "filePath": "models.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/status": {
      "filePath": "status.tsx"
    },
    "/toolbox": {
      "filePath": "toolbox.tsx"
    },
    "/c/$chatId": {
      "filePath": "c.$chatId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
