// Renders a Material Symbols (Outlined) glyph from the local sprite at
// src/assets/icons.svg via <use>, instead of the ligature icon font.
//
// Why: the ligature approach (`<span class="material-symbols-outlined">
// rocket_launch</span>`) fails ugly -- a missing or misspelled glyph renders
// the literal English word as body text. A missing <use> target here instead
// renders nothing (an empty box), and the SymbolName union type below turns a
// typo into a compile error in the first place, so that failure mode should
// never reach runtime.
//
// The sprite itself, and the ICON_NAMES list between the markers below, are
// generated by scripts/build-icon-sprite.mjs -- run it after adding a new
// `<Icon name="...">` usage so both stay in sync. Everything outside the
// marked block is hand-written and untouched by that script.

import { ensureIconSprite } from './iconSprite'

// Inline the sprite before the first icon renders. Same-document fragment
// references resolve; the cross-document form this file used to rely on did
// not -- see iconSprite.ts for what was measured.
ensureIconSprite()

// AUTO-GENERATED ICON_NAMES START -- see scripts/build-icon-sprite.mjs
export const ICON_NAMES = [
  'arrow_drop_down',
  'arrow_range',
  'arrow_upward',
  'bakery_dining',
  'bolt',
  'bookmark',
  'bookmark_added',
  'brightness_auto',
  'build',
  'cancel',
  'chat_bubble',
  'check',
  'check_circle',
  'close',
  'cloud',
  'code',
  'confirmation_number',
  'construction',
  'content_copy',
  'dark_mode',
  'delete',
  'delete_sweep',
  'deployed_code',
  'dictionary',
  'download',
  'download_2',
  'download_done',
  'edit',
  'edit_square',
  'error',
  'flight',
  'folder',
  'forum',
  'functions',
  'home_repair_service',
  'keep',
  'language',
  'light_mode',
  'lightbulb',
  'lock',
  'lock_open',
  'memory',
  'menu_book',
  'monitor_heart',
  'mood',
  'neurology',
  'notifications',
  'open_in_new',
  'palette',
  'pause',
  'pets',
  'phone_locked',
  'play_arrow',
  'raven',
  'record_voice_over',
  'regular_expression',
  'restart_alt',
  'robot_2',
  'rocket_launch',
  'sailing',
  'schedule',
  'search',
  'send',
  'settings',
  'smart_toy',
  'spa',
  'stop',
  'storefront',
  'sync',
  'sync_alt',
  'system_update_alt',
  'tab_close',
  'terminal',
  'warning',
  'wifi',
] as const
// AUTO-GENERATED ICON_NAMES END

/** Every glyph name available in the sprite. Passing anything else to <Icon> is a compile error. */
export type SymbolName = (typeof ICON_NAMES)[number]

/**
 * Icon sizes used across the design: the touch/dense chip sizes (14-19px),
 * the two common control sizes (20/22px). Anything else should go through the
 * `className` escape hatch rather than growing this union without a design
 * reason.
 */
// Pixel size. Deliberately a plain number: the design uses 14-22px, but a
// fixed union forces every consumer needing 26px for a dialog glyph to either
// lie about its size or patch this file, and a px measurement is not an enum.
export type IconSize = number

export interface IconProps {
  /** Glyph name, matching a symbol id generated into src/assets/icons.svg. */
  name: SymbolName
  /** Pixel size for both width and height. Defaults to 20, the most common control size. */
  size?: IconSize
  /**
   * Use the filled (FILL 1) variant. Only a subset of icons ship a filled
   * symbol -- see FILL_ICON_NAMES in scripts/build-icon-sprite.mjs (the nav
   * rail destinations, the dim sum glyph, and the app-logo picker glyphs).
   * Requesting `fill` on a name outside that set renders nothing, the same
   * way any other missing symbol id would.
   */
  fill?: boolean
  className?: string
}

/**
 * A single Material Symbols (Outlined) glyph, rendered from the local sprite.
 *
 * `<use>` points at a bare `#ms-<name>` fragment, resolved against the sprite
 * that iconSprite.ts inlines into the document at module load.
 *
 * This file previously referenced the built asset URL instead, on the stated
 * belief that "WebView2 (Chromium) fully supports cross-document `<use>`
 * fragment references". It does not, under the conditions this app serves
 * under. Measured in the real built application: the sprite fetched with
 * HTTP 200, the hrefs and symbol ids matched exactly, and every `<use>`
 * reported a 0x0 bounding box with no instanceRoot -- every icon in the
 * product was an empty box, silently, and the comment asserting otherwise is
 * why nobody looked.
 */
export function Icon({ name, size = 20, fill = false, className }: IconProps) {
  const symbolId = fill ? `ms-${name}-fill` : `ms-${name}`
  return (
    <svg
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden="true"
      className={className}
    >
      <use href={`#${symbolId}`} />
    </svg>
  )
}
